module.exports = {
    MODEL_CONSTANTS: {
        ORDER_SUMMARY: "ORDER_SUMMARY",
        ORDER_LIST: "ORDER_LIST",
        ORDER_DETAILS: "ORDER_DETAILS",
        INVOICE_SUMMARY: "INVOICE_SUMMARY",
        CUSTOMER_PERMISSION: "CUSTOMER_PERMISSION",
    },
    PERMISSION_CONSTANTS: {
        READ_ORDER_LIST: "READ_ORDER_LIST",
        READ_ORDER_DETAILS: "READ_ORDER_DETAILS",
        CREATE_ORDER: "CREATE_ORDER",
        UPDATE_ORDER: "UPDATE_ORDER",
        CREATE_INVOICE: "CREATE_INVOICE",
    }
}